/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedAccountingRouteImport } from './routes/_authenticated/accounting'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedJoinRouteImport } from './routes/_authenticated/join'
import { Route as AuthenticatedPartiesRouteImport } from './routes/_authenticated/parties'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as AuthenticatedAccountingIndexRouteImport } from './routes/_authenticated/accounting.index'
import { Route as AuthenticatedAccountingDayBookRouteImport } from './routes/_authenticated/accounting.day-book'
import { Route as AuthenticatedAccountingLedgersRouteImport } from './routes/_authenticated/accounting.ledgers'
import { Route as AuthenticatedAccountingTrialBalanceRouteImport } from './routes/_authenticated/accounting.trial-balance'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin.companies'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedPurchasesIndexRouteImport } from './routes/_authenticated/purchases.index'
import { Route as AuthenticatedPurchasesNewRouteImport } from './routes/_authenticated/purchases.new'
import { Route as AuthenticatedSalesIndexRouteImport } from './routes/_authenticated/sales.index'
import { Route as AuthenticatedSalesInvoiceIdRouteImport } from './routes/_authenticated/sales.$invoiceId'
import { Route as AuthenticatedSalesNewRouteImport } from './routes/_authenticated/sales.new'
import { Route as AuthenticatedAdminCompaniesCompanyIdRouteImport } from './routes/_authenticated/admin.companies_.$companyId'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin.users_.$userId'
import { Route as ApiPublicHealthOtpRouteImport } from './routes/api/public/health/otp'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountingRoute = AuthenticatedAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJoinRoute = AuthenticatedJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartiesRoute = AuthenticatedPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountingIndexRoute =
  AuthenticatedAccountingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingDayBookRoute =
  AuthenticatedAccountingDayBookRouteImport.update({
    id: '/day-book',
    path: '/day-book',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingLedgersRoute =
  AuthenticatedAccountingLedgersRouteImport.update({
    id: '/ledgers',
    path: '/ledgers',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingTrialBalanceRoute =
  AuthenticatedAccountingTrialBalanceRouteImport.update({
    id: '/trial-balance',
    path: '/trial-balance',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPurchasesIndexRoute =
  AuthenticatedPurchasesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPurchasesRoute,
  } as any)
const AuthenticatedPurchasesNewRoute =
  AuthenticatedPurchasesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPurchasesRoute,
  } as any)
const AuthenticatedSalesIndexRoute = AuthenticatedSalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSalesRoute,
} as any)
const AuthenticatedSalesInvoiceIdRoute =
  AuthenticatedSalesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthenticatedSalesRoute,
  } as any)
const AuthenticatedSalesNewRoute = AuthenticatedSalesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedSalesRoute,
} as any)
const AuthenticatedAdminCompaniesCompanyIdRoute =
  AuthenticatedAdminCompaniesCompanyIdRouteImport.update({
    id: '/companies_/$companyId',
    path: '/companies/$companyId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/users_/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHealthOtpRoute = ApiPublicHealthOtpRouteImport.update({
  id: '/api/public/health/otp',
  path: '/api/public/health/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accounting': typeof AuthenticatedAccountingRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/join': typeof AuthenticatedJoinRoute
  '/parties': typeof AuthenticatedPartiesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/purchases': typeof AuthenticatedPurchasesRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/invite/$code': typeof InviteCodeRoute
  '/accounting/day-book': typeof AuthenticatedAccountingDayBookRoute
  '/accounting/ledgers': typeof AuthenticatedAccountingLedgersRoute
  '/accounting/trial-balance': typeof AuthenticatedAccountingTrialBalanceRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/sales/$invoiceId': typeof AuthenticatedSalesInvoiceIdRoute
  '/sales/new': typeof AuthenticatedSalesNewRoute
  '/accounting/': typeof AuthenticatedAccountingIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/sales/': typeof AuthenticatedSalesIndexRoute
  '/admin/companies/$companyId': typeof AuthenticatedAdminCompaniesCompanyIdRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/health/otp': typeof ApiPublicHealthOtpRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/join': typeof AuthenticatedJoinRoute
  '/parties': typeof AuthenticatedPartiesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/invite/$code': typeof InviteCodeRoute
  '/accounting/day-book': typeof AuthenticatedAccountingDayBookRoute
  '/accounting/ledgers': typeof AuthenticatedAccountingLedgersRoute
  '/accounting/trial-balance': typeof AuthenticatedAccountingTrialBalanceRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/sales/$invoiceId': typeof AuthenticatedSalesInvoiceIdRoute
  '/sales/new': typeof AuthenticatedSalesNewRoute
  '/accounting': typeof AuthenticatedAccountingIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/purchases': typeof AuthenticatedPurchasesIndexRoute
  '/sales': typeof AuthenticatedSalesIndexRoute
  '/admin/companies/$companyId': typeof AuthenticatedAdminCompaniesCompanyIdRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/health/otp': typeof ApiPublicHealthOtpRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/accounting': typeof AuthenticatedAccountingRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/join': typeof AuthenticatedJoinRoute
  '/_authenticated/parties': typeof AuthenticatedPartiesRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/invite/$code': typeof InviteCodeRoute
  '/_authenticated/accounting/day-book': typeof AuthenticatedAccountingDayBookRoute
  '/_authenticated/accounting/ledgers': typeof AuthenticatedAccountingLedgersRoute
  '/_authenticated/accounting/trial-balance': typeof AuthenticatedAccountingTrialBalanceRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/_authenticated/sales/$invoiceId': typeof AuthenticatedSalesInvoiceIdRoute
  '/_authenticated/sales/new': typeof AuthenticatedSalesNewRoute
  '/_authenticated/accounting/': typeof AuthenticatedAccountingIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/_authenticated/sales/': typeof AuthenticatedSalesIndexRoute
  '/_authenticated/admin/companies_/$companyId': typeof AuthenticatedAdminCompaniesCompanyIdRoute
  '/_authenticated/admin/users_/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/health/otp': typeof ApiPublicHealthOtpRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/accounting'
    | '/admin'
    | '/dashboard'
    | '/expenses'
    | '/join'
    | '/parties'
    | '/payments'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/team'
    | '/invite/$code'
    | '/accounting/day-book'
    | '/accounting/ledgers'
    | '/accounting/trial-balance'
    | '/admin/audit'
    | '/admin/companies'
    | '/admin/users'
    | '/purchases/new'
    | '/sales/$invoiceId'
    | '/sales/new'
    | '/accounting/'
    | '/admin/'
    | '/purchases/'
    | '/sales/'
    | '/admin/companies/$companyId'
    | '/admin/users/$userId'
    | '/api/public/health/otp'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/dashboard'
    | '/expenses'
    | '/join'
    | '/parties'
    | '/payments'
    | '/products'
    | '/reports'
    | '/settings'
    | '/team'
    | '/invite/$code'
    | '/accounting/day-book'
    | '/accounting/ledgers'
    | '/accounting/trial-balance'
    | '/admin/audit'
    | '/admin/companies'
    | '/admin/users'
    | '/purchases/new'
    | '/sales/$invoiceId'
    | '/sales/new'
    | '/accounting'
    | '/admin'
    | '/purchases'
    | '/sales'
    | '/admin/companies/$companyId'
    | '/admin/users/$userId'
    | '/api/public/health/otp'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/_authenticated/accounting'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/join'
    | '/_authenticated/parties'
    | '/_authenticated/payments'
    | '/_authenticated/products'
    | '/_authenticated/purchases'
    | '/_authenticated/reports'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/invite/$code'
    | '/_authenticated/accounting/day-book'
    | '/_authenticated/accounting/ledgers'
    | '/_authenticated/accounting/trial-balance'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/users'
    | '/_authenticated/purchases/new'
    | '/_authenticated/sales/$invoiceId'
    | '/_authenticated/sales/new'
    | '/_authenticated/accounting/'
    | '/_authenticated/admin/'
    | '/_authenticated/purchases/'
    | '/_authenticated/sales/'
    | '/_authenticated/admin/companies_/$companyId'
    | '/_authenticated/admin/users_/$userId'
    | '/api/public/health/otp'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  InviteCodeRoute: typeof InviteCodeRoute
  ApiPublicHealthOtpRoute: typeof ApiPublicHealthOtpRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounting': {
      id: '/_authenticated/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AuthenticatedAccountingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/join': {
      id: '/_authenticated/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AuthenticatedJoinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parties': {
      id: '/_authenticated/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof AuthenticatedPartiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounting/': {
      id: '/_authenticated/accounting/'
      path: '/'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AuthenticatedAccountingIndexRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/day-book': {
      id: '/_authenticated/accounting/day-book'
      path: '/day-book'
      fullPath: '/accounting/day-book'
      preLoaderRoute: typeof AuthenticatedAccountingDayBookRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/ledgers': {
      id: '/_authenticated/accounting/ledgers'
      path: '/ledgers'
      fullPath: '/accounting/ledgers'
      preLoaderRoute: typeof AuthenticatedAccountingLedgersRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/trial-balance': {
      id: '/_authenticated/accounting/trial-balance'
      path: '/trial-balance'
      fullPath: '/accounting/trial-balance'
      preLoaderRoute: typeof AuthenticatedAccountingTrialBalanceRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/purchases/': {
      id: '/_authenticated/purchases/'
      path: '/'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AuthenticatedPurchasesIndexRouteImport
      parentRoute: typeof AuthenticatedPurchasesRoute
    }
    '/_authenticated/purchases/new': {
      id: '/_authenticated/purchases/new'
      path: '/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof AuthenticatedPurchasesNewRouteImport
      parentRoute: typeof AuthenticatedPurchasesRoute
    }
    '/_authenticated/sales/': {
      id: '/_authenticated/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof AuthenticatedSalesIndexRouteImport
      parentRoute: typeof AuthenticatedSalesRoute
    }
    '/_authenticated/sales/$invoiceId': {
      id: '/_authenticated/sales/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/sales/$invoiceId'
      preLoaderRoute: typeof AuthenticatedSalesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedSalesRoute
    }
    '/_authenticated/sales/new': {
      id: '/_authenticated/sales/new'
      path: '/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof AuthenticatedSalesNewRouteImport
      parentRoute: typeof AuthenticatedSalesRoute
    }
    '/_authenticated/admin/companies_/$companyId': {
      id: '/_authenticated/admin/companies_/$companyId'
      path: '/companies/$companyId'
      fullPath: '/admin/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users_/$userId': {
      id: '/_authenticated/admin/users_/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/health/otp': {
      id: '/api/public/health/otp'
      path: '/api/public/health/otp'
      fullPath: '/api/public/health/otp'
      preLoaderRoute: typeof ApiPublicHealthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAccountingRouteChildren {
  AuthenticatedAccountingDayBookRoute: typeof AuthenticatedAccountingDayBookRoute
  AuthenticatedAccountingLedgersRoute: typeof AuthenticatedAccountingLedgersRoute
  AuthenticatedAccountingTrialBalanceRoute: typeof AuthenticatedAccountingTrialBalanceRoute
  AuthenticatedAccountingIndexRoute: typeof AuthenticatedAccountingIndexRoute
}

const AuthenticatedAccountingRouteChildren: AuthenticatedAccountingRouteChildren =
  {
    AuthenticatedAccountingDayBookRoute: AuthenticatedAccountingDayBookRoute,
    AuthenticatedAccountingLedgersRoute: AuthenticatedAccountingLedgersRoute,
    AuthenticatedAccountingTrialBalanceRoute:
      AuthenticatedAccountingTrialBalanceRoute,
    AuthenticatedAccountingIndexRoute: AuthenticatedAccountingIndexRoute,
  }

const AuthenticatedAccountingRouteWithChildren =
  AuthenticatedAccountingRoute._addFileChildren(
    AuthenticatedAccountingRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCompaniesCompanyIdRoute: typeof AuthenticatedAdminCompaniesCompanyIdRoute
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminCompaniesRoute: AuthenticatedAdminCompaniesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCompaniesCompanyIdRoute:
    AuthenticatedAdminCompaniesCompanyIdRoute,
  AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPurchasesRouteChildren {
  AuthenticatedPurchasesNewRoute: typeof AuthenticatedPurchasesNewRoute
  AuthenticatedPurchasesIndexRoute: typeof AuthenticatedPurchasesIndexRoute
}

const AuthenticatedPurchasesRouteChildren: AuthenticatedPurchasesRouteChildren =
  {
    AuthenticatedPurchasesNewRoute: AuthenticatedPurchasesNewRoute,
    AuthenticatedPurchasesIndexRoute: AuthenticatedPurchasesIndexRoute,
  }

const AuthenticatedPurchasesRouteWithChildren =
  AuthenticatedPurchasesRoute._addFileChildren(
    AuthenticatedPurchasesRouteChildren,
  )

interface AuthenticatedSalesRouteChildren {
  AuthenticatedSalesInvoiceIdRoute: typeof AuthenticatedSalesInvoiceIdRoute
  AuthenticatedSalesNewRoute: typeof AuthenticatedSalesNewRoute
  AuthenticatedSalesIndexRoute: typeof AuthenticatedSalesIndexRoute
}

const AuthenticatedSalesRouteChildren: AuthenticatedSalesRouteChildren = {
  AuthenticatedSalesInvoiceIdRoute: AuthenticatedSalesInvoiceIdRoute,
  AuthenticatedSalesNewRoute: AuthenticatedSalesNewRoute,
  AuthenticatedSalesIndexRoute: AuthenticatedSalesIndexRoute,
}

const AuthenticatedSalesRouteWithChildren =
  AuthenticatedSalesRoute._addFileChildren(AuthenticatedSalesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountingRoute: typeof AuthenticatedAccountingRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedJoinRoute: typeof AuthenticatedJoinRoute
  AuthenticatedPartiesRoute: typeof AuthenticatedPartiesRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountingRoute: AuthenticatedAccountingRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedJoinRoute: AuthenticatedJoinRoute,
  AuthenticatedPartiesRoute: AuthenticatedPartiesRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  InviteCodeRoute: InviteCodeRoute,
  ApiPublicHealthOtpRoute: ApiPublicHealthOtpRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
